### ISSUE TITLE
useMemo不具备预期的缓存行为

### ISSUE THREAD

**Issue by ahzvenol** [wulongshe/micro-reactive#15]
测试版本 micro-reactive：`2.6.4`，`2.8.1`

使用环境 solid-js：`1.8.17`

测试代码如下
```
const singal = useReactive(0)
const memo = useMemo(() => singal() * 2)
createEffect(() => console.log(memo()))
singal(0)
singal(1)
singal(1)
```
预期输出`0` `2`,实际输出`0` `0` `2` `2`

使用的时候并没有特意验证所以没有发觉，看源码发现好像没有缓存，测试发现确实没有

正如api文档所说的，“useMemo与useComputed的区别在于，useMemo只能返回只读计算属性，且只有最顶层可进行函数调用(read)”

记录一下这个情况，如果有同样使用这个库的朋友可以有所参考

解决方案：使用solidjs提供的`createMemo`即可获得预期的缓存行为

**Comment by wulongshe** [comment]
micro-reactive@2.9.1中useMemo新增了依赖数组
