### ISSUE TITLE
关于await useReactive({})会被错误识别的问题

### ISSUE THREAD

**Issue by ahzvenol** [wulongshe/micro-reactive#3]
测试版本 "micro-reactive": "^2.3.3"

一开始是用了一个`async () => useReactive({})`发现一直是pending状态

经过测试发现是useReactive({}).then会返回一个value是null的Signal，因为是个函数所以被错误的当成一个能够await的对象了

`await useReactive({})`和`await { then: () => { } }`造成的效果一样，都是导致接下来程序的阻塞

因为这个库的运行模式要用signal(value)来赋值，不知道作者有没有办法解决这个问题，或者是提醒一下用户？

目前的话我是用`[useReactive({})]`，在外面再`[0]`取值绕开这个问题

**Comment by wulongshe** [comment]
出现该问题的原因在于`async function`会将返回值通过`Promise.resolve`进行隐式的转换，无论返回值是什么，其最终都会被转换为`promise`对象。

Promise.resolve的工作原理可简单描述如下：
```js
Promise.resolve = (val) => {
  return typeof val?.then === 'function'
    // 有then方法，则调用then取值，并使用新的promise包裹
    ? new Promise((resolve, reject) => val.then(resolve, reject))
    // 没有then方法，直接使用promise包裹
    : new Promise((resolve) => resolve(val))
}
```

运行
```js
const state = useReactive({})
cosnt func = () => console.log('run func')
state.then(func)
```
时，`func`将被作为值赋给`state.func`，但`func`函数不会被运行，既`val.then(resolve, reject)`中的`resolve`不会被执行，因此`promise`会一直时`pending`状态。


在`async function`中返回一个带`then`的对象，是会出现报错提示的。
![image](https://github.com/wulongshe/micro-reactive/assets/116495705/9d6459ee-773c-4329-8196-bd7cb799dd8b)

解决方案是，增加兜底逻辑：若原对象中未显式声名`then`属性，则不允许后续再添加和获取`then`属性
