### ISSUE TITLE
和Vue工作时使用v-if导致的依赖收集问题

### ISSUE THREAD

**Issue by ahzvenol** [wulongshe/micro-reactive#5]
测试版本 
`"micro-reactive": "latest", "vue": "^3.2.37"`(micro-reactive-cli中指定的版本)
 `"micro-reactive": "^2.5.0", "vue": "^3.3.4"`(我的一个项目的版本) 

这个问题是挺早遇到的了，简化后的代码如下
```vue
<template>
    <div v-if="bool()">
        <div>{{ data() }}</div>
    </div>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useEffect, useReactive } from 'micro-reactive'
const bool = useReactive(false)
const data = useReactive("1")
useEffect(() => console.log(data()))
onMounted(() => setTimeout(() => bool(true), 1000))
onMounted(() => setTimeout(() => data("2"), 2000))
</script>
```
控制台会正常输出`1` `2`，但页面并不会改变，保持为`1`

打log发现ReactiveEffect.run只会在组件初始化时运行一次，这时候bool()为false，v-if块内的表达式并不运行，data()的使用就没有被收集到了，而如果使用Vue自己的ref，则会在bool()改变之后再运行一次ReactiveEffect.run，重新收集依赖

目前缓解这个问题的方式是bool()为true之后主动调用一次`getCurrentInstance()!.update()`，这样接下来可以恢复正常

**Comment by wulongshe** [comment]
出现该问题的原因是：组件只会在初始化阶段收集一次依赖，更新阶段并没有收集新增的依赖
解决方案：在依赖函数被触发时，再次执行收集依赖的操作
修复版本：micro-reactive：v2.6.0
